[package]
name = "getkhulan-com"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
khulan = { path = "./khulan" } # TODO: use the external crate

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["handlebars", "tera"]
